"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['__main__.py']
APP_NAME = "Kalaupapa"
DATA_FILES = ['monika-2.qml', 'monikaconfig.qrc', 'monikaqrc.py', '__main__.py', 'qtquicksontrols2.conf']
OPTIONS = {
    'iconfile': '/Users/marquiskurt/PycharmProjects/kalaupapa/img/icon.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Configure and Deploy Robots",
        'CFBundleIdentifier': "edu.damien.kalaupapa",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2018, Damien MechaMonarchs, GNU GPL v3"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
